# Generated by Django 3.1.2 on 2020-11-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood_app', '0002_neighbourhood_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(choices=[('1', 'Kikuyu'), ('2', 'Dagoretti'), ('3', 'Karen'), ('4', 'Kabete'), ('5', 'Kasarani'), ('6', 'Rongai'), ('7', 'Westland'), ('8', 'Parkland')], max_length=200),
        ),
    ]
