# Generated by Django 3.1.2 on 2020-11-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood_app', '0004_auto_20201104_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='contact_fire',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='contact_health',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='contact_police',
            field=models.CharField(default='', max_length=20),
        ),
    ]
