# Generated by Django 3.1.2 on 2020-11-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood_app', '0006_auto_20201104_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(choices=[(' Kikuyu ', 'Kikuyu'), ('Dago', 'Dagoretti'), ('Karen', 'Karen'), ('Kabete', 'Kabete'), ('Kasarani', 'Kasarani'), ('Rongai', 'Rongai'), ('Westie', 'Westland'), ('Parkie', 'Parkland')], max_length=200),
        ),
    ]
